/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 innova-with-footstep.glb
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export const FootStep = (props) => {
  const { nodes, materials } = useGLTF("/innova-with-footstep.glb");
  return (
    <group
      {...props}
      dispose={null}
      rotation={[0, Math.PI / 0.8, 0]}
      scale={0.085}
    >
      <group
        position={[-1.35, 0.47, -23.15]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <group position={[0, 0.89, 0.55]}>
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL001.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:243:254:177"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL002.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:243:254:177.001"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL003.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:243:254:177.002"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL004.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL005.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL006.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL007.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL008.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL009.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL010.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL011.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL012.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL013.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL014.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL015.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL016.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL017.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL018.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL019.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL020.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL021.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL022.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL023.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL024.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL025.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL026.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL027.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL028.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL029.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL030.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL031.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL032.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL033.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL034.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL035.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL036.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL037.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL038.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL039.geometry}
            material={materials["Composite Rubber"]}
            position={[-786.97, 1721.96, -484.93]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL040.geometry}
            material={materials["Composite Rubber"]}
            position={[-786.97, -1019.2, -202.35]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL041.geometry}
            material={materials["Composite Rubber"]}
            position={[787.11, 1438.23, -334.94]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL042.geometry}
            material={materials["Composite Rubber"]}
            position={[787.11, -1026.44, -485.95]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL043.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL044.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1050.24, -520.65]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL045.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1077.15, -553.19]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL046.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1107.86, -582.17]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL047.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1141.95, -607.05]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL048.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1178.95, -627.27]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL049.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1218.21, -642.49]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL050.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1258.97, -652.78]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL051.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1300.4, -657.7]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL052.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:73:73:73.013"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL053.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1341.89, -656.47]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL054.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:73:73:73.015"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL055.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL056.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL057.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL058.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL059.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL060.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL061.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL062.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL063.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL064.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL065.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL066.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL067.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL068.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:73:73:73.029"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL069.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL070.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL071.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL072.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL073.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL074.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL075.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL076.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:73:73:73.037"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL077.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL078.geometry}
            material={materials["Toyota_Innova_VEHICLE_MODEL:color:128:64:64"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL079.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:128:64:64.001"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL080.geometry}
            material={materials["Black gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL081.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1383.08, -648.94]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL082.geometry}
            material={materials["Black gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL083.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1423.25, -636.24]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL084.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1461.54, -618.66]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL085.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1497.26, -596.23]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL086.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1529.8, -569.33]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL087.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1558.78, -538.61]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL088.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1583.65, -504.52]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL089.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1603.87, -467.53]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL090.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1619.09, -428.26]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL091.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1629.38, -387.51]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL092.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1634.3, -346.08]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL093.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1633.08, -304.58]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL094.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1625.54, -263.4]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL095.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1612.84, -223.23]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL096.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1595.26, -184.94]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL097.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1572.83, -149.22]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL098.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1545.93, -116.68]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL099.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1515.22, -87.7]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL100.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1481.12, -62.82]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL101.geometry}
            material={materials["Black gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL102.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1444.13, -42.6]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL103.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1404.86, -27.38]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL104.geometry}
            material={materials["Black gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL105.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1364.11, -17.1]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL106.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1322.68, -12.17]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL107.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1281.18, -13.4]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL108.geometry}
            material={materials["Black gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL109.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1240, -20.94]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL110.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1199.83, -33.63]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL111.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1161.54, -51.21]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL112.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1125.82, -73.64]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL113.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1093.28, -100.54]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL114.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1064.3, -131.26]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL115.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1039.43, -165.35]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL116.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1019.2, -202.35]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL117.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1003.99, -241.61]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL118.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -1010.24, -446.65]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL119.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -997.54, -406.48]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL120.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -990, -365.29]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL121.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -988.78, -323.79]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL122.geometry}
            material={materials["Composite Rubber"]}
            position={[786.16, -993.7, -282.36]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL141.geometry}
            material={materials["Black gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL142.geometry}
            material={materials["Black gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL143.geometry}
            material={materials["Black gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL144.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL145.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL146.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL147.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL148.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL149.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL150.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL151.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL152.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL153.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL154.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL155.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL156.geometry}
            material={materials["tail light"]}
            position={[745.74, -2082.54, -1171.12]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL157.geometry}
            material={materials["tail light"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL158.geometry}
            material={materials["tail light"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL159.geometry}
            material={materials["tail light"]}
            position={[498.58, -2151.03, -1167.28]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL160.geometry}
            material={materials["tail light"]}
            position={[-745.74, -2082.54, -1171.12]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL161.geometry}
            material={materials["tail light"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL162.geometry}
            material={materials["tail light"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL163.geometry}
            material={materials["tail light"]}
            position={[-498.58, -2151.03, -1167.28]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL164.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:255:0:0.008"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL165.geometry}
            material={materials["tail light"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL166.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:255:0:0.010"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL167.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:255:0:0.011"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL168.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:255:0:0.012"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL169.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:255:0:0.013"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL170.geometry}
            material={materials["tail light"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL171.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:255:0:0.015"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL172.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:255:0:0.016"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL173.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:255:0:0.017"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL174.geometry}
            material={materials["tail light"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL175.geometry}
            material={materials.Silv}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL176.geometry}
            material={materials["Mirror indicator"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL177.geometry}
            material={materials.Silv}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL178.geometry}
            material={materials.Silv}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL179.geometry}
            material={materials["Basic glass new"]}
            position={[798.49, 2040.44, -584.94]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL180.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL181.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL182.geometry}
            material={materials.Silv}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL183.geometry}
            material={materials["Mirror indicator"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL184.geometry}
            material={materials.Silv}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL185.geometry}
            material={materials.Silv}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL186.geometry}
            material={materials["Basic glass new"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL187.geometry}
            material={materials["B gls"]}
            position={[641.63, 1932.23, -893.36]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL188.geometry}
            material={materials["B gls"]}
            position={[-641.6, 1932.16, -893.37]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL189.geometry}
            material={materials["tail light indi"]}
            position={[747.81, -2124.7, -958.67]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL190.geometry}
            material={materials["tail light indi"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL191.geometry}
            material={materials["tail light indi"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL192.geometry}
            material={materials["tail light indi"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL193.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL194.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL195.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL196.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL197.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL198.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL199.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL200.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL201.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL202.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL203.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL204.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL205.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL206.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL207.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL208.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL209.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL210.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL211.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL212.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL213.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL214.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL215.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL216.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL217.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL218.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL219.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL220.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL223.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL237.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL297.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL372.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL373.geometry}
            material={materials["White Paint"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL374.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL375.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL376.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL377.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL378.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL379.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL380.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL381.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL382.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL383.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL384.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL385.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL386.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL387.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL388.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL389.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL390.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL391.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL392.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL393.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL394.geometry}
            material={materials["Car Seat"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL395.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL396.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL397.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL398.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL399.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL400.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL401.geometry}
            material={materials["Black semi gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL402.geometry}
            material={materials["Mirror indicator"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL403.geometry}
            material={materials["Mirror indicator"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL404.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL405.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL406.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL407.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL408.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL409.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL410.geometry}
            material={materials["Composite Rubber"]}
            position={[-758.21, 1438.24, -334.95]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL411.geometry}
            material={materials["Composite Rubber"]}
            position={[-758.21, -1311.53, -334.95]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL412.geometry}
            material={materials["Tyre alloy black"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL413.geometry}
            material={materials["Tyre alloy black"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL414.geometry}
            material={materials["Tyre alloy black"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL415.geometry}
            material={materials["Tyre alloy black"]}
            position={[-760, 1438.22, -335.24]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL416.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL417.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL418.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL419.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL420.geometry}
            material={materials["Metal gloss"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL421.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL422.geometry}
            material={materials["Metal gloss"]}
            position={[-782.26, 1440.87, -332.74]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL423.geometry}
            material={materials.Cylinder_1}
            position={[-741.37, 1441, -332.73]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL424.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL425.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL426.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL427.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL428.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:153:147:191.004"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL429.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL430.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL431.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL432.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL433.geometry}
            material={materials.Cylinder_1}
            position={[-775.74, 1326.85, -384.26]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL434.geometry}
            material={materials.Cylinder_1}
            position={[-764.42, 1325.2, -379]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL435.geometry}
            material={materials.Cylinder_1}
            position={[-744.72, 1301.19, -393.57]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL436.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL437.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL438.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL439.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL440.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL441.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL442.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL443.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL444.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL445.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL446.geometry}
            material={materials.Cylinder_1}
            position={[-849.64, 1454.81, -385.49]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL447.geometry}
            material={materials.Cylinder_1}
            position={[-849.64, 1394.95, -365.87]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL448.geometry}
            material={materials.Cylinder_1}
            position={[-849.64, 1395.12, -302.88]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL449.geometry}
            material={materials.Cylinder_1}
            position={[-849.64, 1455.08, -283.57]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL450.geometry}
            material={materials.Cylinder_1}
            position={[-849.64, 1491.97, -334.63]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL451.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL452.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL453.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL454.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL455.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL456.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL457.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL458.geometry}
            material={materials.Cylinder_1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL459.geometry}
            material={materials.Cylinder_1}
            position={[-851.98, 1438.4, -335.14]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL460.geometry}
            material={
              materials["Toyota_Innova_VEHICLE_MODEL:color:73:73:73.039"]
            }
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL461.geometry}
            material={materials["Tyre alloy black"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL462.geometry}
            material={materials["Tyre alloy black"]}
            position={[-852.61, 1438.4, -335.16]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL463.geometry}
            material={materials["Tyre alloy black"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL466.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL513.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL514.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL515.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL516.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL518.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL519.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL520.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL521.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL522.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL523.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL524.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL525.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL526.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL527.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL528.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL529.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL530.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL531.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL532.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL533.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL534.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL535.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL536.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL537.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL538.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL539.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL540.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL541.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL542.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL543.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL544.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL545.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL546.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL547.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL548.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL549.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL550.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL551.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL552.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL553.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL554.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL555.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL556.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL557.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL558.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL559.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL560.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL561.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL562.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL563.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL564.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL565.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL566.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL567.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL568.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL569.geometry}
            material={materials["Composite Rubber"]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL570.geometry}
            material={materials["Composite Rubber"]}
            position={[-788.52, 1438.23, -334.94]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL571.geometry}
            material={materials["Composite Rubber"]}
            position={[-728.5, 1721.96, -484.93]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL619.geometry}
            material={materials["Composite Rubber"]}
            position={[-680.45, 1438.23, -334.94]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL620.geometry}
            material={materials["Composite Rubber"]}
            position={[-836.43, 1438.23, -334.94]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL621.geometry}
            material={materials["Composite Rubber"]}
            position={[-758.44, 1438.24, -334.95]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL622.geometry}
            material={materials["Composite Rubber"]}
            position={[-868.21, 1436.84, -335.06]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL665.geometry}
            material={materials["Composite Rubber"]}
            position={[-728.5, -1019.2, -202.35]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL672.geometry}
            material={materials["Composite Rubber"]}
            position={[-680.45, -1311.54, -334.94]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL673.geometry}
            material={materials["Composite Rubber"]}
            position={[-836.43, -1311.54, -334.94]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL674.geometry}
            material={materials["Composite Rubber"]}
            position={[-758.44, -1311.53, -334.95]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL675.geometry}
            material={materials["Composite Rubber"]}
            position={[-868.21, -1312.93, -335.06]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL676.geometry}
            material={materials.Silv}
            position={[744.58, -2116.04, -960.52]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL677.geometry}
            material={materials.Silv}
            position={[428.65, -2201.59, -1137.8]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL678.geometry}
            material={materials.Silv}
            position={[-747.46, -2116.04, -960.52]}
            rotation={[-Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL679.geometry}
            material={materials.Silv}
            position={[-431.54, -2201.59, -1137.8]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL680.geometry}
            material={materials.Cylinder_1}
            position={[-865.22, 1438.29, -335.25]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL681.geometry}
            material={materials.Cylinder_1}
            position={[-865.22, -1311.48, -335.25]}
            rotation={[Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL682.geometry}
            material={materials.Silv}
            position={[745.74, -2058.53, -1171.12]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL683.geometry}
            material={materials.Silv}
            position={[498.58, -2127.02, -1167.28]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL684.geometry}
            material={materials.Silv}
            position={[-745.74, -2058.53, -1171.12]}
          />
          <mesh
            geometry={nodes.Toyota_Innova_VEHICLE_MODEL685.geometry}
            material={materials.Silv}
            position={[-498.58, -2127.02, -1167.28]}
          />
          <mesh
            geometry={nodes.mesh124.geometry}
            material={materials["Black gloss"]}
          />
          <mesh
            geometry={nodes.mesh124_1.geometry}
            material={materials["Black semi gloss"]}
          />
        </group>
      </group>
      <group
        position={[-10.29, 3.32, -22.56]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.01}
      >
        <group position={[61.5, 10.29, -38.51]}>
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP001.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP002.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP003.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP004.geometry}
            material={materials["CRYSTA FOOT STEP:color:210:210:255"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP005.geometry}
            material={materials["Cylinder_1.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP006.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP007.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP008.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP009.geometry}
            material={materials["CRYSTA FOOT STEP:color:243:254:177.003"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP010.geometry}
            material={materials["CRYSTA FOOT STEP:color:243:254:177.004"]}
          />
        </group>
      </group>
      <group
        position={[7.61, 3.32, -22.56]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={-0.01}
      >
        <group position={[61.5, 10.29, -38.51]}>
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP012.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP013.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP014.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP015.geometry}
            material={materials["CRYSTA FOOT STEP:color:210:210:255"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP016.geometry}
            material={materials["Cylinder_1.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP017.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP018.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP019.geometry}
            material={materials["Black semi gloss.002"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP020.geometry}
            material={materials["CRYSTA FOOT STEP:color:243:254:177.003"]}
          />
          <mesh
            geometry={nodes.CRYSTA_FOOT_STEP021.geometry}
            material={materials["CRYSTA FOOT STEP:color:243:254:177.004"]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/innova-with-footstep.glb");
